name: NoSpawnChunks
main: net.dmulloy2.nospawnchunksplus.NoSpawnChunks
version: ${project.version} (Build ${project.build.number})
description: Helps manage server memory by dynamically unloading chunks
author: dmulloy2
commands:
  nsc:
    description: NoSpawnChunks root command
    usage: /<command> <args>
permissions:
  nospawnchunks.reload:
    default: op
  nospawnchunks.unloadchunks:
    default: op